/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PestsIndexRouteImport } from './routes/pests/index'
import { Route as PestsPestNameRouteImport } from './routes/pests/$pestName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PestsIndexRoute = PestsIndexRouteImport.update({
  id: '/pests/',
  path: '/pests/',
  getParentRoute: () => rootRouteImport,
} as any)
const PestsPestNameRoute = PestsPestNameRouteImport.update({
  id: '/pests/$pestName',
  path: '/pests/$pestName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pests/$pestName': typeof PestsPestNameRoute
  '/pests': typeof PestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pests/$pestName': typeof PestsPestNameRoute
  '/pests': typeof PestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pests/$pestName': typeof PestsPestNameRoute
  '/pests/': typeof PestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pests/$pestName' | '/pests'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pests/$pestName' | '/pests'
  id: '__root__' | '/' | '/pests/$pestName' | '/pests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PestsPestNameRoute: typeof PestsPestNameRoute
  PestsIndexRoute: typeof PestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pests/': {
      id: '/pests/'
      path: '/pests'
      fullPath: '/pests'
      preLoaderRoute: typeof PestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pests/$pestName': {
      id: '/pests/$pestName'
      path: '/pests/$pestName'
      fullPath: '/pests/$pestName'
      preLoaderRoute: typeof PestsPestNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PestsPestNameRoute: PestsPestNameRoute,
  PestsIndexRoute: PestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
